---
title: "Figure 2: Combine separate plots into one"
author: "Vlada Milchevskaya"
#date: "11.11.20"
output: 
    prettydoc::html_pretty:
        toc: true
        theme: cayman
        highlight: github
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library("animalBreeding")
library(ggplot2)
library(ggpubr)
library(fields)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(ggplot2)
library(directlabels)
source("./helper_function_fig2.R")
```

# Load individual plots 

Individual figures are described each in their corresponding HTML:

[Fig 2A](./fig2a/fig2A.html)

[Fig 2B](./fig2b/fig2B.html)

[Fig 2C](./fig2c/fig2c.html)

[Fig 2C](./fig2d/fig2D.html)

The fixed parameters for the breeding setup are:

Average litter size of 7, effective fertility of 70% and,
except for the contour plots, the required confidence of 90%. 


```{r}
load("fig2a/gg_plots_2A.Rdata")
load("fig2b/gg_plot_2B.Rdata")
load("fig2c/gg_plot_2C.Rdata")
load("fig2d/gg_plot_2D.Rdata")
```

# Wrap-up 

Remove labels where needed, set plots in correct proportions.

```{r}
# deal with labels on the contour plot
my.dl <- list(box.color=NA, "draw.rects")

# remove labels including X axis
remove_labels_legend <- theme(
  axis.title.x=element_blank(),
  axis.text.x=element_blank(),
  #axis.ticks.x=element_blank(),
  axis.title.y=element_blank(),
  #axis.text.y=element_blank(),
  #axis.ticks.y=element_blank(),
  #legend.position = "none",
  title = element_blank()
  )

# empty plot for spacing
empty_plot <- ggplot() + theme_void()
```

```{r}
plot2A_hist_empty <- plot2A_hist + remove_labels_legend
plot2A_points_empty <- plot2A_points + theme(
  axis.title.y=element_blank(),
  title = element_blank()
  )

plot2B_empty <- plot2B + remove_labels_legend

plot2C_empty <- plot2C + theme(
  axis.title.y=element_blank(),
  title = element_blank()
  )
plot2D_empty <- plot2Dann + theme(
  axis.title.y=element_blank(),
  title = element_blank()
  )

# merge the two plots for pannel A
bb <- ggarrange(plot2A_hist_empty, 
                plot2A_points_empty + scale_color_brewer(palette = "Dark2"),
                    ncol = 1, nrow = 2, heights = c(1,3))
```

```{r}
left_panel <- ggarrange(
  plotlist = list(
      bb,
      empty_plot,
      plot2B + theme(
  #axis.ticks.x=element_blank(),
  axis.title.y=element_blank(),
  #axis.text.y=element_blank(),
  #axis.ticks.y=element_blank(),
  #legend.position = "none",
  title = element_blank()
  )), 
  ncol=1, 
  nrow = 3,
  heights = c(1.6,0.1,1))

right_panel <- ggarrange(
  plotlist = list(
    empty_plot,
      plot2C_empty, 
      empty_plot,
      plot2D_empty), 
  ncol=1, 
  nrow = 4,
  heights = c(0.1,1,0.3,1.6))
          #ncol=1)

figure2 <- ggarrange(left_panel, empty_plot, right_panel, ncol=3, 
                     widths = c(1.6,0.2,1))

# looks better in proper size ..
figure2
ggsave(figure2, file = "Figure_2_nolabels.pdf",height = 210, width = 297, units = "mm")
```
